version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: finance-postgres
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finance-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge
